Add french translation
allure-framework/allure2 pull request #1151
Opened 2020-11-03 15:30 UTC by ZDGN-for-Git

### Context
Adding translation file for french language

2020-11-03 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/allure-framework/allure2?pullRequest=1151) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/allure-framework/allure2?pullRequest=1151) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/allure-framework/allure2?pullRequest=1151) it.</sub>

2020-11-03 15:48 UTC, nantes44-github requested changes
ligne 52 : pourquoi le "C" en majuscule?
ligne 161 : un "e" en trop
ligne 175 : il y a une faute d'orthographe (il manque un S)

2020-11-03 15:52 UTC, nantes44-github requested changes

2020-11-03 15:52 UTC, nantes44-github commented on allure-generator/src/main/javascript/translations/fr.json
> +      "name": "Tendance des Categories"
Pourquoi le C majuscule?

2020-11-03 15:52 UTC, nantes44-github commented on allure-generator/src/main/javascript/translations/fr.json
> +    "language": "Changeer de langue",
il y a un "e" en trop

2020-11-03 15:52 UTC, nantes44-github commented on allure-generator/src/main/javascript/translations/fr.json
> +      "groups": "Basculer les information des groupes",
il manqu un 's'

2020-11-03 15:56 UTC, nantes44-github approved these changes

2020-11-03 15:57 UTC, ZDGN-for-Git commented on allure-generator/src/main/javascript/translations/fr.json
> +      "name": "Tendance des Categories"
Corrigé avec 8742d46

2020-11-03 15:57 UTC, ZDGN-for-Git commented on allure-generator/src/main/javascript/translations/fr.json
> +    "language": "Changeer de langue",
Corrigé avec 8742d46

2020-11-03 15:58 UTC, ZDGN-for-Git commented on allure-generator/src/main/javascript/translations/fr.json
> +      "groups": "Basculer les information des groupes",
Corrigé avec 8742d46

2020-11-03 15:59 UTC, nantes44-github approved these changes

2020-11-05 11:53 UTC, baev approved these changes

2020-11-05 11:59 UTC, baev commented
you also need to include it to `translations.js` file, plus add translations for plugins. As an example, see https://github.com/allure-framework/allure2/commit/769283cd0a4cdeb74b05cf46b05869dabff10a9e

2020-11-05 12:00 UTC, baev commented
the demo report for this PR available at https://ci.qameta.io/job/allure2/job/PR-1151/Demo_20Report/index.html

2020-11-05 13:11 UTC, merged

2020-11-05 13:12 UTC, baev commented
@ZDGN-for-Git thanks! 👍