Make results' limits configurable (fixes #347)
allure-framework/allure2 pull request #1331
Opened 2021-06-23 12:33 UTC by sskorol

### Context
There were several places in code with hardcoded limits for items rendered on charts. It was really inconvenient for the end-user who had to rebuild the entire project to make limits configurable.

This fix moves the actual configuration into an Aggregator interface which is implemented by key plugins. Moreover, a user can now control the limits via `RESULTS_LIMIT` env variable that could be set before the report's generation. Note that a newly added method was intentionally made static as some of the APIs that adjust the limits are also static.

Fixes #347

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2021-11-10 14:06 UTC, indradeepchowdhury commented
Hello, Just checking to see if there is a possibility of this PR to get merged soon and what it would take to get this merged :)

Thank you.

2021-11-11 04:50 UTC, indradeepchowdhury approved these changes
LGTM!

2021-11-11 09:35 UTC, sskorol commented
@indradeepchowdhury as far as I remember, @baev had some concerns in terms of implementation. Need to double-check with him.

2021-11-12 05:20 UTC, indradeepchowdhury commented
> @indradeepchowdhury as far as I remember, @baev had some concerns in terms of implementation. Need to double-check with him.

Thanks for the update @sskorol. @baev would it be possible to expedite this feature. This would be a super cool feature to have.

2021-12-20 09:02 UTC, pbandura commented
Hi @sskorol. Thanks for jour work on providing such feature.
I've got one question - do you still work on this or has it been parked?

2021-12-20 19:24 UTC, sskorol commented
Hi @pbandura, I don't. When I initially pushed it, it was a fully working feature. I talked to maintainers directly. And they promised to check. Seems like they didn't have time. Now I see there's a conflict. I can resolve it. And then you will be able to build a new version with this feature from sources if it's important for you.

2021-12-21 01:01 UTC, indradeepchowdhury commented
Hi @sskorol I think this feature would be pretty cool and I am looking forward to using it. This feature will allow us to align the history with our Sprint duration or even let us increase the history limit to a month for proper tracking 🙂

2021-12-21 09:16 UTC, sskorol commented
@indradeepchowdhury @pbandura force-pushed changes with conflicts' resolution. Now you can build the report on your own with this feature.

2022-10-05 03:04 UTC, sangheee commented
@sskorol @indradeepchowdhury @baev Why didn't you guys apply this?

2022-10-05 05:20 UTC, baev commented
I don't like the current implementation because:

1. Plugin API changes -- new method introduced in Aggregator interface may create some issues for other users
2. The env variable processing is unsafe -- You can set negative or non-number env variable and crash your report generation
3. There are no tests provided

Besides that, our team is heavily focused on Allure 3 development right now, so this change isn't really in priority right now

2024-05-03 19:55 UTC, A1exKH requested changes
Code LGTM.

Please resolve conflicts for this PR.

2025-01-25 15:12 UTC, CloneOfAlex approved these changes

2025-01-26 09:23 UTC, jennyliangxj commented
Unsubscribe

On Sat, Jan 25, 2025 at 11:12 PM CloneOfAlex ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/allure-framework/allure2/pull/1331#pullrequestreview-2574033904>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMOK4L5CE2KMISKK6WNZFL2MOSWDAVCNFSM6AAAAABV3N5ZPWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNZUGAZTGOJQGQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-01-26 09:46 UTC, A1exKH approved these changes
LGTM.
Please resolve conflicts for this PR.

2025-01-27 10:42 UTC, closed without merging

2025-01-27 10:42 UTC, baev commented
the issue is fixed in Allure 3 https://github.com/allure-framework/allure3