Clickable solves #395
allure-framework/allure2 pull request #1497
Opened 2021-11-26 14:15 UTC by jk816vu

### Context

#### Checklist
- [ ] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2021-11-26 23:09 UTC, jk816vu commented
i have no idea how to add label

2021-11-29 16:43 UTC, jk816vu commented
@baev Hi i also wanted to update tooltip for few seconds 
`this.setAttribute('data-tooltip', 'Text copied!')`
Problem is when i do it in web browser console, it updates without issue. 

If i do it inside `onClick` it does not update the view of the affected tooltip. When i later print out the `data-tooltip` value in console instead it prints out my new value. What i am trying to say is that value in data-tooltip does not match what is in console. What could be the issue here ? 
on website:
![image](https://user-images.githubusercontent.com/37405331/143907870-fb3b3118-e51f-4900-b2f9-94a40b3d2659.png)
in console:
![image](https://user-images.githubusercontent.com/37405331/143907895-5eb8b03f-64bd-4500-a3ee-40860528f16b.png)

2021-11-30 11:22 UTC, baev requested changes

2021-11-30 11:22 UTC, baev commented on allure-generator/src/main/javascript/plugins/testresult-duration/DurationView.hbs
> +        onclick="navigator.clipboard.writeText('{{date time.start}} {{time time.start}} - {{time time.stop}}');"
please use `{{> ../../blocks/clipboard-copy/clipboard-copy value=...}}`  instead. See https://github.com/allure-framework/allure2/blob/8aa23ba7d84ccb4742f499bf4a79e2255f943dca/allure-generator/src/main/javascript/components/testresult/TestResultView.hbs#L3

2023-08-24 15:04 UTC, closed without merging