Add support for supplying input zip files next to directories
allure-framework/allure2 pull request #1544
Opened 2022-01-04 14:37 UTC by miensol

With this change it is possible to run
`allure generate --report-dir ./out ./source-1.zip ./source-2.zip ./source-3`

### Context

We're building a POC that would bring together tests results from various CI jobs. 
We've attempted to run allure from AWS Lambda. Raw tests results are synced from S3 to an EFS attached to Lambda. The performance of generating the report is terrible when compared to local execution. It turned out that the majority of the time the lambda spends on checking files metadata. This is understandable as allure needs to list files and directories. 

In order to tackle this, we'd like to zip test results i.e. thousands of files, sync the archives to the EFS attached to the Lambda instead of raw test results. 

The way it was implemented was to run readers (except the zip results source plugin) again after opening the zip archive.

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2024-03-05 07:26 UTC, noomorph commented
The feature looks promising! However, I was wondering if it would be possible to add equal support for `*.tar` and `*.tar.gz` archives as well.

The motivation behind TAR archives is especially interesting for custom Allure runtime writers. If a writer appends files (like `9283749-result.json` and `2384978923-container.json`) straight to a tar archive instead of a directory, it can unload the filesystem from operations related to directory/file management, without even having to compress things. I believe this could significantly improve performance, especially on 5000-6000 test suites.

2024-05-03 19:49 UTC, A1exKH requested changes
Code LGTM.

Please resolve conflicts for this PR.

2025-01-25 15:11 UTC, CloneOfAlex approved these changes

2025-03-11 19:45 UTC, CloneOfAlex approved these changes

2026-04-11 00:58 UTC, felseje commented
Hey, please, resolve conflicts for this PR.

2026-08-10 09:35 UTC, baev commented
Allure 3 supports report generation from dump archives

2026-08-10 09:35 UTC, closed without merging