fix regression issue: one more fix for the layout of step stats
allure-framework/allure2 pull request #2015
Opened 2023-06-13 09:13 UTC by valfirst

The regression issue is introduced in #1993:
![issue](https://github.com/allure-framework/allure2/assets/5081226/6324976e-5dc9-44cc-b657-cfdfd255d9b1)

After the fix from this PR:
![fix](https://github.com/allure-framework/allure2/assets/5081226/aaa18930-ebcd-4143-8d62-e9d3851873da)

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

2023-06-14 12:56 UTC, baev requested changes
Could you please provide a simple result json so I can validate the change?

2023-06-28 10:19 UTC, baev commented
@valfirst

2023-07-03 15:07 UTC, valfirst commented
@baev please check this file (zipped as GH doesn't allow to attach JSON): [ff1af1c1-8c1f-48dd-a783-cbb2425b82a4-result.json.zip](https://github.com/allure-framework/allure2/files/11938127/ff1af1c1-8c1f-48dd-a783-cbb2425b82a4-result.json.zip)

2023-07-24 17:55 UTC, merged

2023-07-24 17:55 UTC, baev commented
@valfirst thanks!